# Generated by Django 5.1.5 on 2026-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_branding_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branding', models.CharField(choices=[('FESTIVAL', 'Festival'), ('BURGERS', 'Burgers')], db_index=True, default='FESTIVAL', max_length=10)),
                ('from_location', models.CharField(choices=[('MAIN', 'Principal'), ('SECONDARY', 'Secundario')], default='MAIN', max_length=12)),
                ('to_location', models.CharField(choices=[('MAIN', 'Principal'), ('SECONDARY', 'Secundario')], default='SECONDARY', max_length=12)),
                ('first_id', models.CharField(max_length=32)),
                ('last_id', models.CharField(max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='operator',
            name='location',
            field=models.CharField(choices=[('MAIN', 'Principal'), ('SECONDARY', 'Secundario'), ('BOTH', 'Ambos')], db_index=True, default='MAIN', max_length=12),
        ),
        migrations.AddField(
            model_name='pizzaitem',
            name='current_location',
            field=models.CharField(choices=[('MAIN', 'Principal'), ('SECONDARY', 'Secundario')], db_index=True, default='MAIN', max_length=12),
        ),
        migrations.AddField(
            model_name='pizzaitem',
            name='sold_location',
            field=models.CharField(blank=True, choices=[('MAIN', 'Principal'), ('SECONDARY', 'Secundario')], db_index=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='from_location',
            field=models.CharField(blank=True, choices=[('MAIN', 'Principal'), ('SECONDARY', 'Secundario')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='to_location',
            field=models.CharField(blank=True, choices=[('MAIN', 'Principal'), ('SECONDARY', 'Secundario')], default='', max_length=12),
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branding', models.CharField(choices=[('FESTIVAL', 'Festival'), ('BURGERS', 'Burgers')], db_index=True, default='FESTIVAL', max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('prefix', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('branding', 'name'), name='uniq_flavor_branding_name'), models.UniqueConstraint(fields=('branding', 'prefix'), name='uniq_flavor_branding_prefix')],
            },
        ),
    ]
