# Generated by Django 5.1.5 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0006_alter_operator_role_alter_scanevent_actor_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operator",
            name="role",
            field=models.CharField(
                choices=[
                    ("KITCHEN", "Kitchen"),
                    ("SALES", "Sales"),
                    ("BATCHES", "Batches"),
                    ("OPERATOR", "Operator"),
                    ("CASHIER_OPS", "Cashier operations"),
                    ("SOCIO", "Socio"),
                    ("ADMIN", "Admin"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="scanevent",
            name="actor_role",
            field=models.CharField(
                choices=[
                    ("COCINA", "Cocina"),
                    ("VENTAS", "Ventas"),
                    ("OPERADOR", "Operador"),
                    ("CAJA OPERACION", "Caja operacion"),
                    ("ADMIN", "Admin"),
                ],
                max_length=16,
            ),
        ),
    ]
