from django.urls import path

from . import views

urlpatterns = [
    path("", views.landing_view, name="landing"),
    path("login/", views.landing_view, name="login-legacy"),
    path("festival/login/", views.festival_login_view, name="festival-login"),
    path("don/login/", views.don_login_view, name="don-login"),
    path("logout/", views.logout_view, name="logout"),
    path("app/", views.home_view, name="home"),
    path("branding/select", views.branding_select_view, name="branding-select"),
    path("kitchen/", views.kitchen_view, name="kitchen"),
    path("sales/", views.sales_view, name="sales"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("inventory/", views.inventory_view, name="inventory"),
    path("batches/", views.batches_view, name="batches"),
    path("admin-ops/", views.admin_ops_view, name="admin-ops"),
    path("api/flavors", views.FlavorAPIView.as_view(), name="api-flavors"),
    path("api/flavors/inactive", views.InactiveFlavorAPIView.as_view(), name="api-flavors-inactive"),
    path("api/flavors/<int:flavor_id>", views.FlavorDetailAPIView.as_view(), name="api-flavor-detail"),
    path("api/flavors/<int:flavor_id>/deactivate", views.FlavorDeactivateAPIView.as_view(), name="api-flavor-deactivate"),
    path("api/flavors/<int:flavor_id>/reactivate", views.FlavorReactivateAPIView.as_view(), name="api-flavor-reactivate"),
    path("api/kitchen/bulk-ready", views.KitchenBulkReadyAPIView.as_view(), name="api-kitchen-bulk-ready"),
    path("api/scan", views.ScanAPIView.as_view(), name="api-scan"),
    path("api/dashboard", views.DashboardDataAPIView.as_view(), name="api-dashboard"),
    path("api/dashboard/sales-export.xls", views.SalesExportXLSAPIView.as_view(), name="api-dashboard-sales-export"),
    path("api/inventory", views.InventoryDataAPIView.as_view(), name="api-inventory"),
    path("api/waiters", views.WaiterAPIView.as_view(), name="api-waiters"),
    path("api/waiters/labels.pdf", views.WaiterLabelsAPIView.as_view(), name="api-waiters-labels"),
    path("api/batches/generate", views.BatchGenerateAPIView.as_view(), name="api-batches-generate"),
    path("api/batches", views.BatchListAPIView.as_view(), name="api-batches-list"),
    path("api/batches/<str:batch_code>/labels.pdf", views.BatchLabelsAPIView.as_view(), name="api-batches-labels"),
    path("api/admin/status", views.AdminStatusAPIView.as_view(), name="api-admin-status"),
    path("api/admin/undo", views.UndoAPIView.as_view(), name="api-admin-undo"),
    path("api/admin/verify-pin", views.AdminVerifyPinAPIView.as_view(), name="api-admin-verify-pin"),
    path("api/batches/verify-admin-pin", views.BatchAdminVerifyPinAPIView.as_view(), name="api-batches-verify-admin-pin"),
    path("api/admin/transfer-to-secondary", views.TransferToSecondaryAPIView.as_view(), name="api-admin-transfer"),
    path("api/admin/return-to-main", views.ReturnToMainAPIView.as_view(), name="api-admin-return"),
]
